export const PUBLIC_ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  CART: "/cart",
  WISHLIST: "/wishlist",
  COURSE: "/courses",
  COURSE_DETAIL: "/course/:id",
  PAYMENT: "/payment",
};


export const PRIVATE_ROUTES = {
  DASHBOARD: "/dashboard",
  DASHBOARD_COURSES: "/dashboard/courses",
  DASHBOARD_COURSES_CREATE: "/dashboard/courses/create",
  DASHBOARD_COURSES_EDIT: "/dashboard/courses/:courseId/edit",
  DASHBOARD_COURSE_CATEGORIES: "/dashboard/course-categories",
  DASHBOARD_COURSE_TAGS: "/dashboard/course-tags",
  DASHBOARD_STAFF: "/dashboard/staff",
  DASHBOARD_STAFF_CREATE: "/dashboard/staff/create",
  DASHBOARD_STAFF_EDIT: "/dashboard/staff/:staffId/edit",
  DASHBOARD_PERMISSIONS: "/dashboard/permissions",
  DASHBOARD_PERMISSIONS_CREATE: "/dashboard/permissions/create",
  DASHBOARD_PERMISSIONS_EDIT: "/dashboard/permissions/:permissionId/edit",
  DASHBOARD_ROLES: "/dashboard/roles",
  DASHBOARD_ROLES_CREATE: "/dashboard/roles/create",
  DASHBOARD_ROLES_EDIT: "/dashboard/roles/:roleId/edit",
  DASHBOARD_STUDENTS: "/dashboard/students",
  DASHBOARD_STUDENTS_CREATE: "/dashboard/students/create",
  DASHBOARD_STUDENTS_EDIT: "/dashboard/students/:studentId/edit",
  DASHBOARD_ATTENDANCE: "/dashboard/attendance",
  DASHBOARD_ASSIGNMENTS: "/dashboard/assignments",
  DASHBOARD_TEACHERS: "/dashboard/teachers",
  DASHBOARD_TEACHERS_CREATE: "/dashboard/teachers/create",
  DASHBOARD_TEACHERS_EDIT: "/dashboard/teachers/:teacherId/edit",
  DASHBOARD_TEACHING_SCHEDULE: "/dashboard/teaching-schedule",
  DASHBOARD_FINANCE_CASHFLOW: "/dashboard/finance/cashflow",
  DASHBOARD_FINANCE_CASHFLOW_CREATE: "/dashboard/finance/cashflow/create",
  DASHBOARD_FINANCE_CASHFLOW_EDIT: "/dashboard/finance/cashflow/:cashflowId/edit",
  DASHBOARD_FINANCE_INVOICES: "/dashboard/finance/invoices",
  DASHBOARD_FINANCE_INVOICES_CREATE: "/dashboard/finance/invoices/create",
  DASHBOARD_FINANCE_INVOICES_EDIT: "/dashboard/finance/invoices/:invoiceId/edit",
  DASHBOARD_DOCUMENTS: "/dashboard/documents",
  DASHBOARD_DOCUMENTS_CREATE: "/dashboard/documents/create",
  DASHBOARD_DOCUMENTS_EDIT: "/dashboard/documents/:documentId/edit",
  DASHBOARD_CLASSES: "/dashboard/classes",
  DASHBOARD_CLASSES_CREATE: "/dashboard/classes/create",
  DASHBOARD_CLASSES_EDIT: "/dashboard/classes/:classId/edit",
};
